FROM ghcr.io/ferrory/bootc-demo-base:stream9

COPY etc etc
COPY usr usr

# install required packages and enable services
RUN dnf -y install \
        WALinuxAgent \
        cloud-init \
        cloud-utils-growpart \
        gdisk \
        hyperv-daemons && \
    dnf clean all && \
    systemctl enable NetworkManager.service waagent.service cloud-init.service && \
    echo 'ClientAliveInterval 180' >> /etc/ssh/sshd_config

# configure waagent for cloud-init to handle provisioning
RUN sed -i 's/Provisioning.Agent=auto/Provisioning.Agent=cloud-init/g' /etc/waagent.conf && \
    sed -i 's/ResourceDisk.Format=y/ResourceDisk.Format=n/g' /etc/waagent.conf && \
    sed -i 's/ResourceDisk.EnableSwap=y/ResourceDisk.EnableSwap=n/g' /etc/waagent.conf

RUN bootc container lint
